#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Intranet")]
	public partial class SimplyPaymentCardDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertRecon_DataReceived(Recon_DataReceived instance);
    partial void UpdateRecon_DataReceived(Recon_DataReceived instance);
    partial void DeleteRecon_DataReceived(Recon_DataReceived instance);
    partial void InsertRecon_DataProcessed(Recon_DataProcessed instance);
    partial void UpdateRecon_DataProcessed(Recon_DataProcessed instance);
    partial void DeleteRecon_DataProcessed(Recon_DataProcessed instance);
    partial void InsertRecon_JobNumber(Recon_JobNumber instance);
    partial void UpdateRecon_JobNumber(Recon_JobNumber instance);
    partial void DeleteRecon_JobNumber(Recon_JobNumber instance);
    partial void InsertRecon_DocType(Recon_DocType instance);
    partial void UpdateRecon_DocType(Recon_DocType instance);
    partial void DeleteRecon_DocType(Recon_DocType instance);
    partial void InsertRecon_Division(Recon_Division instance);
    partial void UpdateRecon_Division(Recon_Division instance);
    partial void DeleteRecon_Division(Recon_Division instance);
    partial void InsertRecon_Tracking(Recon_Tracking instance);
    partial void UpdateRecon_Tracking(Recon_Tracking instance);
    partial void DeleteRecon_Tracking(Recon_Tracking instance);
    #endregion
		
		public SimplyPaymentCardDataContext() : 
				base(global::DataAccessLayer.Properties.Settings.Default.IntranetConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SimplyPaymentCardDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SimplyPaymentCardDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SimplyPaymentCardDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SimplyPaymentCardDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Recon_DataReceived> Recon_DataReceiveds
		{
			get
			{
				return this.GetTable<Recon_DataReceived>();
			}
		}
		
		public System.Data.Linq.Table<Recon_DataProcessed> Recon_DataProcesseds
		{
			get
			{
				return this.GetTable<Recon_DataProcessed>();
			}
		}
		
		public System.Data.Linq.Table<Recon_JobNumber> Recon_JobNumbers
		{
			get
			{
				return this.GetTable<Recon_JobNumber>();
			}
		}
		
		public System.Data.Linq.Table<Recon_DocType> Recon_DocTypes
		{
			get
			{
				return this.GetTable<Recon_DocType>();
			}
		}
		
		public System.Data.Linq.Table<Recon_Division> Recon_Divisions
		{
			get
			{
				return this.GetTable<Recon_Division>();
			}
		}
		
		public System.Data.Linq.Table<Recon_Tracking> Recon_Trackings
		{
			get
			{
				return this.GetTable<Recon_Tracking>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recon_DataReceived")]
	public partial class Recon_DataReceived : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DR_UID;
		
		private System.Nullable<int> _DR_ClientID;
		
		private System.Nullable<int> _DR_JobID;
		
		private System.Nullable<System.DateTime> _DR_Datetime;
		
		private System.Nullable<int> _DR_TotalReceived;
		
		private System.Nullable<int> _DR_DocType;
		
		private string _DR_FileName;
		
		private System.Nullable<int> _DR_DPUID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDR_UIDChanging(int value);
    partial void OnDR_UIDChanged();
    partial void OnDR_ClientIDChanging(System.Nullable<int> value);
    partial void OnDR_ClientIDChanged();
    partial void OnDR_JobIDChanging(System.Nullable<int> value);
    partial void OnDR_JobIDChanged();
    partial void OnDR_DatetimeChanging(System.Nullable<System.DateTime> value);
    partial void OnDR_DatetimeChanged();
    partial void OnDR_TotalReceivedChanging(System.Nullable<int> value);
    partial void OnDR_TotalReceivedChanged();
    partial void OnDR_DocTypeChanging(System.Nullable<int> value);
    partial void OnDR_DocTypeChanged();
    partial void OnDR_FileNameChanging(string value);
    partial void OnDR_FileNameChanged();
    partial void OnDR_DPUIDChanging(System.Nullable<int> value);
    partial void OnDR_DPUIDChanged();
    #endregion
		
		public Recon_DataReceived()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DR_UID
		{
			get
			{
				return this._DR_UID;
			}
			set
			{
				if ((this._DR_UID != value))
				{
					this.OnDR_UIDChanging(value);
					this.SendPropertyChanging();
					this._DR_UID = value;
					this.SendPropertyChanged("DR_UID");
					this.OnDR_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_ClientID", DbType="Int")]
		public System.Nullable<int> DR_ClientID
		{
			get
			{
				return this._DR_ClientID;
			}
			set
			{
				if ((this._DR_ClientID != value))
				{
					this.OnDR_ClientIDChanging(value);
					this.SendPropertyChanging();
					this._DR_ClientID = value;
					this.SendPropertyChanged("DR_ClientID");
					this.OnDR_ClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_JobID", DbType="Int")]
		public System.Nullable<int> DR_JobID
		{
			get
			{
				return this._DR_JobID;
			}
			set
			{
				if ((this._DR_JobID != value))
				{
					this.OnDR_JobIDChanging(value);
					this.SendPropertyChanging();
					this._DR_JobID = value;
					this.SendPropertyChanged("DR_JobID");
					this.OnDR_JobIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_Datetime", DbType="DateTime")]
		public System.Nullable<System.DateTime> DR_Datetime
		{
			get
			{
				return this._DR_Datetime;
			}
			set
			{
				if ((this._DR_Datetime != value))
				{
					this.OnDR_DatetimeChanging(value);
					this.SendPropertyChanging();
					this._DR_Datetime = value;
					this.SendPropertyChanged("DR_Datetime");
					this.OnDR_DatetimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_TotalReceived", DbType="Int")]
		public System.Nullable<int> DR_TotalReceived
		{
			get
			{
				return this._DR_TotalReceived;
			}
			set
			{
				if ((this._DR_TotalReceived != value))
				{
					this.OnDR_TotalReceivedChanging(value);
					this.SendPropertyChanging();
					this._DR_TotalReceived = value;
					this.SendPropertyChanged("DR_TotalReceived");
					this.OnDR_TotalReceivedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_DocType", DbType="Int")]
		public System.Nullable<int> DR_DocType
		{
			get
			{
				return this._DR_DocType;
			}
			set
			{
				if ((this._DR_DocType != value))
				{
					this.OnDR_DocTypeChanging(value);
					this.SendPropertyChanging();
					this._DR_DocType = value;
					this.SendPropertyChanged("DR_DocType");
					this.OnDR_DocTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_FileName", DbType="VarChar(50)")]
		public string DR_FileName
		{
			get
			{
				return this._DR_FileName;
			}
			set
			{
				if ((this._DR_FileName != value))
				{
					this.OnDR_FileNameChanging(value);
					this.SendPropertyChanging();
					this._DR_FileName = value;
					this.SendPropertyChanged("DR_FileName");
					this.OnDR_FileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_DPUID", DbType="Int")]
		public System.Nullable<int> DR_DPUID
		{
			get
			{
				return this._DR_DPUID;
			}
			set
			{
				if ((this._DR_DPUID != value))
				{
					this.OnDR_DPUIDChanging(value);
					this.SendPropertyChanging();
					this._DR_DPUID = value;
					this.SendPropertyChanged("DR_DPUID");
					this.OnDR_DPUIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recon_DataProcessed")]
	public partial class Recon_DataProcessed : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DP_UID;
		
		private string _DP_FileName;
		
		private System.Nullable<System.DateTime> _DP_DateProcessed;
		
		private System.Nullable<int> _DP_TotalProcessed;
		
		private System.Nullable<System.DateTime> _ProcessingStarted;
		
		private System.Nullable<System.DateTime> _ProcessingFinished;
		
		private System.Nullable<int> _DP_MailedSets;
		
		private System.Nullable<int> _DP_EmailedSets;
		
		private System.Nullable<int> _DP_MailedPages;
		
		private System.Nullable<int> _DP_MailedImages;
		
		private System.Nullable<int> _DP_ArchSets;
		
		private System.Nullable<int> _DP_Reconcilled;
		
		private System.Nullable<int> _DP_ReturnedSets;
		
		private System.Nullable<int> _DP_MailedRecords;
		
		private System.Nullable<int> _DP_MailedSetsC4;
		
		private System.Nullable<int> _DP_Division;
		
		private string _DR_IDs;
		
		private string _DP_EmailAddress;
		
		private System.Nullable<int> _DP_Images;
		
		private System.Nullable<System.DateTime> _DP_ImagedDate;
		
		private System.Nullable<int> _DP_SetsLodged;
		
		private System.Nullable<int> _DP_ElmsNumber;
		
		private System.Nullable<System.DateTime> _DP_LodgedDate;
		
		private System.Nullable<int> _DP_BUNCarryOverRecords;
		
		private System.Nullable<int> _DP_EmailPages;
		
		private System.Nullable<int> _DP_EmailedImages;
		
		private System.Nullable<int> _DP_EmailedSets2;
		
		private System.Nullable<int> _DP_Ignored;
		
		private System.Nullable<int> _DP_ArchiveOnly;
		
		private System.Nullable<int> _DP_EmailedRecords;
		
		private System.Nullable<int> _DP_ReturnedRecords;
		
		private System.Nullable<int> _DP_PrioritySets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDP_UIDChanging(int value);
    partial void OnDP_UIDChanged();
    partial void OnDP_FileNameChanging(string value);
    partial void OnDP_FileNameChanged();
    partial void OnDP_DateProcessedChanging(System.Nullable<System.DateTime> value);
    partial void OnDP_DateProcessedChanged();
    partial void OnDP_TotalProcessedChanging(System.Nullable<int> value);
    partial void OnDP_TotalProcessedChanged();
    partial void OnProcessingStartedChanging(System.Nullable<System.DateTime> value);
    partial void OnProcessingStartedChanged();
    partial void OnProcessingFinishedChanging(System.Nullable<System.DateTime> value);
    partial void OnProcessingFinishedChanged();
    partial void OnDP_MailedSetsChanging(System.Nullable<int> value);
    partial void OnDP_MailedSetsChanged();
    partial void OnDP_EmailedSetsChanging(System.Nullable<int> value);
    partial void OnDP_EmailedSetsChanged();
    partial void OnDP_MailedPagesChanging(System.Nullable<int> value);
    partial void OnDP_MailedPagesChanged();
    partial void OnDP_MailedImagesChanging(System.Nullable<int> value);
    partial void OnDP_MailedImagesChanged();
    partial void OnDP_ArchSetsChanging(System.Nullable<int> value);
    partial void OnDP_ArchSetsChanged();
    partial void OnDP_ReconcilledChanging(System.Nullable<int> value);
    partial void OnDP_ReconcilledChanged();
    partial void OnDP_ReturnedSetsChanging(System.Nullable<int> value);
    partial void OnDP_ReturnedSetsChanged();
    partial void OnDP_MailedRecordsChanging(System.Nullable<int> value);
    partial void OnDP_MailedRecordsChanged();
    partial void OnDP_MailedSetsC4Changing(System.Nullable<int> value);
    partial void OnDP_MailedSetsC4Changed();
    partial void OnDP_DivisionChanging(System.Nullable<int> value);
    partial void OnDP_DivisionChanged();
    partial void OnDR_IDsChanging(string value);
    partial void OnDR_IDsChanged();
    partial void OnDP_EmailAddressChanging(string value);
    partial void OnDP_EmailAddressChanged();
    partial void OnDP_ImagesChanging(System.Nullable<int> value);
    partial void OnDP_ImagesChanged();
    partial void OnDP_ImagedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDP_ImagedDateChanged();
    partial void OnDP_SetsLodgedChanging(System.Nullable<int> value);
    partial void OnDP_SetsLodgedChanged();
    partial void OnDP_ElmsNumberChanging(System.Nullable<int> value);
    partial void OnDP_ElmsNumberChanged();
    partial void OnDP_LodgedDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDP_LodgedDateChanged();
    partial void OnDP_BUNCarryOverRecordsChanging(System.Nullable<int> value);
    partial void OnDP_BUNCarryOverRecordsChanged();
    partial void OnDP_EmailPagesChanging(System.Nullable<int> value);
    partial void OnDP_EmailPagesChanged();
    partial void OnDP_EmailedImagesChanging(System.Nullable<int> value);
    partial void OnDP_EmailedImagesChanged();
    partial void OnDP_EmailedSets2Changing(System.Nullable<int> value);
    partial void OnDP_EmailedSets2Changed();
    partial void OnDP_IgnoredChanging(System.Nullable<int> value);
    partial void OnDP_IgnoredChanged();
    partial void OnDP_ArchiveOnlyChanging(System.Nullable<int> value);
    partial void OnDP_ArchiveOnlyChanged();
    partial void OnDP_EmailedRecordsChanging(System.Nullable<int> value);
    partial void OnDP_EmailedRecordsChanged();
    partial void OnDP_ReturnedRecordsChanging(System.Nullable<int> value);
    partial void OnDP_ReturnedRecordsChanged();
    partial void OnDP_PrioritySetsChanging(System.Nullable<int> value);
    partial void OnDP_PrioritySetsChanged();
    #endregion
		
		public Recon_DataProcessed()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DP_UID
		{
			get
			{
				return this._DP_UID;
			}
			set
			{
				if ((this._DP_UID != value))
				{
					this.OnDP_UIDChanging(value);
					this.SendPropertyChanging();
					this._DP_UID = value;
					this.SendPropertyChanged("DP_UID");
					this.OnDP_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_FileName", DbType="VarChar(100)")]
		public string DP_FileName
		{
			get
			{
				return this._DP_FileName;
			}
			set
			{
				if ((this._DP_FileName != value))
				{
					this.OnDP_FileNameChanging(value);
					this.SendPropertyChanging();
					this._DP_FileName = value;
					this.SendPropertyChanged("DP_FileName");
					this.OnDP_FileNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_DateProcessed", DbType="DateTime")]
		public System.Nullable<System.DateTime> DP_DateProcessed
		{
			get
			{
				return this._DP_DateProcessed;
			}
			set
			{
				if ((this._DP_DateProcessed != value))
				{
					this.OnDP_DateProcessedChanging(value);
					this.SendPropertyChanging();
					this._DP_DateProcessed = value;
					this.SendPropertyChanged("DP_DateProcessed");
					this.OnDP_DateProcessedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_TotalProcessed", DbType="Int")]
		public System.Nullable<int> DP_TotalProcessed
		{
			get
			{
				return this._DP_TotalProcessed;
			}
			set
			{
				if ((this._DP_TotalProcessed != value))
				{
					this.OnDP_TotalProcessedChanging(value);
					this.SendPropertyChanging();
					this._DP_TotalProcessed = value;
					this.SendPropertyChanged("DP_TotalProcessed");
					this.OnDP_TotalProcessedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingStarted", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProcessingStarted
		{
			get
			{
				return this._ProcessingStarted;
			}
			set
			{
				if ((this._ProcessingStarted != value))
				{
					this.OnProcessingStartedChanging(value);
					this.SendPropertyChanging();
					this._ProcessingStarted = value;
					this.SendPropertyChanged("ProcessingStarted");
					this.OnProcessingStartedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProcessingFinished", DbType="DateTime")]
		public System.Nullable<System.DateTime> ProcessingFinished
		{
			get
			{
				return this._ProcessingFinished;
			}
			set
			{
				if ((this._ProcessingFinished != value))
				{
					this.OnProcessingFinishedChanging(value);
					this.SendPropertyChanging();
					this._ProcessingFinished = value;
					this.SendPropertyChanged("ProcessingFinished");
					this.OnProcessingFinishedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_MailedSets", DbType="Int")]
		public System.Nullable<int> DP_MailedSets
		{
			get
			{
				return this._DP_MailedSets;
			}
			set
			{
				if ((this._DP_MailedSets != value))
				{
					this.OnDP_MailedSetsChanging(value);
					this.SendPropertyChanging();
					this._DP_MailedSets = value;
					this.SendPropertyChanged("DP_MailedSets");
					this.OnDP_MailedSetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_EmailedSets", DbType="Int")]
		public System.Nullable<int> DP_EmailedSets
		{
			get
			{
				return this._DP_EmailedSets;
			}
			set
			{
				if ((this._DP_EmailedSets != value))
				{
					this.OnDP_EmailedSetsChanging(value);
					this.SendPropertyChanging();
					this._DP_EmailedSets = value;
					this.SendPropertyChanged("DP_EmailedSets");
					this.OnDP_EmailedSetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_MailedPages", DbType="Int")]
		public System.Nullable<int> DP_MailedPages
		{
			get
			{
				return this._DP_MailedPages;
			}
			set
			{
				if ((this._DP_MailedPages != value))
				{
					this.OnDP_MailedPagesChanging(value);
					this.SendPropertyChanging();
					this._DP_MailedPages = value;
					this.SendPropertyChanged("DP_MailedPages");
					this.OnDP_MailedPagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_MailedImages", DbType="Int")]
		public System.Nullable<int> DP_MailedImages
		{
			get
			{
				return this._DP_MailedImages;
			}
			set
			{
				if ((this._DP_MailedImages != value))
				{
					this.OnDP_MailedImagesChanging(value);
					this.SendPropertyChanging();
					this._DP_MailedImages = value;
					this.SendPropertyChanged("DP_MailedImages");
					this.OnDP_MailedImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_ArchSets", DbType="Int")]
		public System.Nullable<int> DP_ArchSets
		{
			get
			{
				return this._DP_ArchSets;
			}
			set
			{
				if ((this._DP_ArchSets != value))
				{
					this.OnDP_ArchSetsChanging(value);
					this.SendPropertyChanging();
					this._DP_ArchSets = value;
					this.SendPropertyChanged("DP_ArchSets");
					this.OnDP_ArchSetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_Reconcilled", DbType="Int")]
		public System.Nullable<int> DP_Reconcilled
		{
			get
			{
				return this._DP_Reconcilled;
			}
			set
			{
				if ((this._DP_Reconcilled != value))
				{
					this.OnDP_ReconcilledChanging(value);
					this.SendPropertyChanging();
					this._DP_Reconcilled = value;
					this.SendPropertyChanged("DP_Reconcilled");
					this.OnDP_ReconcilledChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_ReturnedSets", DbType="Int")]
		public System.Nullable<int> DP_ReturnedSets
		{
			get
			{
				return this._DP_ReturnedSets;
			}
			set
			{
				if ((this._DP_ReturnedSets != value))
				{
					this.OnDP_ReturnedSetsChanging(value);
					this.SendPropertyChanging();
					this._DP_ReturnedSets = value;
					this.SendPropertyChanged("DP_ReturnedSets");
					this.OnDP_ReturnedSetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_MailedRecords", DbType="Int")]
		public System.Nullable<int> DP_MailedRecords
		{
			get
			{
				return this._DP_MailedRecords;
			}
			set
			{
				if ((this._DP_MailedRecords != value))
				{
					this.OnDP_MailedRecordsChanging(value);
					this.SendPropertyChanging();
					this._DP_MailedRecords = value;
					this.SendPropertyChanged("DP_MailedRecords");
					this.OnDP_MailedRecordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_MailedSetsC4", DbType="Int")]
		public System.Nullable<int> DP_MailedSetsC4
		{
			get
			{
				return this._DP_MailedSetsC4;
			}
			set
			{
				if ((this._DP_MailedSetsC4 != value))
				{
					this.OnDP_MailedSetsC4Changing(value);
					this.SendPropertyChanging();
					this._DP_MailedSetsC4 = value;
					this.SendPropertyChanged("DP_MailedSetsC4");
					this.OnDP_MailedSetsC4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_Division", DbType="Int")]
		public System.Nullable<int> DP_Division
		{
			get
			{
				return this._DP_Division;
			}
			set
			{
				if ((this._DP_Division != value))
				{
					this.OnDP_DivisionChanging(value);
					this.SendPropertyChanging();
					this._DP_Division = value;
					this.SendPropertyChanged("DP_Division");
					this.OnDP_DivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_IDs", DbType="VarChar(255)")]
		public string DR_IDs
		{
			get
			{
				return this._DR_IDs;
			}
			set
			{
				if ((this._DR_IDs != value))
				{
					this.OnDR_IDsChanging(value);
					this.SendPropertyChanging();
					this._DR_IDs = value;
					this.SendPropertyChanged("DR_IDs");
					this.OnDR_IDsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_EmailAddress", DbType="VarChar(255)")]
		public string DP_EmailAddress
		{
			get
			{
				return this._DP_EmailAddress;
			}
			set
			{
				if ((this._DP_EmailAddress != value))
				{
					this.OnDP_EmailAddressChanging(value);
					this.SendPropertyChanging();
					this._DP_EmailAddress = value;
					this.SendPropertyChanged("DP_EmailAddress");
					this.OnDP_EmailAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_Images", DbType="Int")]
		public System.Nullable<int> DP_Images
		{
			get
			{
				return this._DP_Images;
			}
			set
			{
				if ((this._DP_Images != value))
				{
					this.OnDP_ImagesChanging(value);
					this.SendPropertyChanging();
					this._DP_Images = value;
					this.SendPropertyChanged("DP_Images");
					this.OnDP_ImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_ImagedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DP_ImagedDate
		{
			get
			{
				return this._DP_ImagedDate;
			}
			set
			{
				if ((this._DP_ImagedDate != value))
				{
					this.OnDP_ImagedDateChanging(value);
					this.SendPropertyChanging();
					this._DP_ImagedDate = value;
					this.SendPropertyChanged("DP_ImagedDate");
					this.OnDP_ImagedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_SetsLodged", DbType="Int")]
		public System.Nullable<int> DP_SetsLodged
		{
			get
			{
				return this._DP_SetsLodged;
			}
			set
			{
				if ((this._DP_SetsLodged != value))
				{
					this.OnDP_SetsLodgedChanging(value);
					this.SendPropertyChanging();
					this._DP_SetsLodged = value;
					this.SendPropertyChanged("DP_SetsLodged");
					this.OnDP_SetsLodgedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_ElmsNumber", DbType="Int")]
		public System.Nullable<int> DP_ElmsNumber
		{
			get
			{
				return this._DP_ElmsNumber;
			}
			set
			{
				if ((this._DP_ElmsNumber != value))
				{
					this.OnDP_ElmsNumberChanging(value);
					this.SendPropertyChanging();
					this._DP_ElmsNumber = value;
					this.SendPropertyChanged("DP_ElmsNumber");
					this.OnDP_ElmsNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_LodgedDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DP_LodgedDate
		{
			get
			{
				return this._DP_LodgedDate;
			}
			set
			{
				if ((this._DP_LodgedDate != value))
				{
					this.OnDP_LodgedDateChanging(value);
					this.SendPropertyChanging();
					this._DP_LodgedDate = value;
					this.SendPropertyChanged("DP_LodgedDate");
					this.OnDP_LodgedDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_BUNCarryOverRecords", DbType="Int")]
		public System.Nullable<int> DP_BUNCarryOverRecords
		{
			get
			{
				return this._DP_BUNCarryOverRecords;
			}
			set
			{
				if ((this._DP_BUNCarryOverRecords != value))
				{
					this.OnDP_BUNCarryOverRecordsChanging(value);
					this.SendPropertyChanging();
					this._DP_BUNCarryOverRecords = value;
					this.SendPropertyChanged("DP_BUNCarryOverRecords");
					this.OnDP_BUNCarryOverRecordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_EmailPages", DbType="Int")]
		public System.Nullable<int> DP_EmailPages
		{
			get
			{
				return this._DP_EmailPages;
			}
			set
			{
				if ((this._DP_EmailPages != value))
				{
					this.OnDP_EmailPagesChanging(value);
					this.SendPropertyChanging();
					this._DP_EmailPages = value;
					this.SendPropertyChanged("DP_EmailPages");
					this.OnDP_EmailPagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_EmailedImages", DbType="Int")]
		public System.Nullable<int> DP_EmailedImages
		{
			get
			{
				return this._DP_EmailedImages;
			}
			set
			{
				if ((this._DP_EmailedImages != value))
				{
					this.OnDP_EmailedImagesChanging(value);
					this.SendPropertyChanging();
					this._DP_EmailedImages = value;
					this.SendPropertyChanged("DP_EmailedImages");
					this.OnDP_EmailedImagesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_EmailedSets2", DbType="Int")]
		public System.Nullable<int> DP_EmailedSets2
		{
			get
			{
				return this._DP_EmailedSets2;
			}
			set
			{
				if ((this._DP_EmailedSets2 != value))
				{
					this.OnDP_EmailedSets2Changing(value);
					this.SendPropertyChanging();
					this._DP_EmailedSets2 = value;
					this.SendPropertyChanged("DP_EmailedSets2");
					this.OnDP_EmailedSets2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_Ignored", DbType="Int")]
		public System.Nullable<int> DP_Ignored
		{
			get
			{
				return this._DP_Ignored;
			}
			set
			{
				if ((this._DP_Ignored != value))
				{
					this.OnDP_IgnoredChanging(value);
					this.SendPropertyChanging();
					this._DP_Ignored = value;
					this.SendPropertyChanged("DP_Ignored");
					this.OnDP_IgnoredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_ArchiveOnly", DbType="Int")]
		public System.Nullable<int> DP_ArchiveOnly
		{
			get
			{
				return this._DP_ArchiveOnly;
			}
			set
			{
				if ((this._DP_ArchiveOnly != value))
				{
					this.OnDP_ArchiveOnlyChanging(value);
					this.SendPropertyChanging();
					this._DP_ArchiveOnly = value;
					this.SendPropertyChanged("DP_ArchiveOnly");
					this.OnDP_ArchiveOnlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_EmailedRecords", DbType="Int")]
		public System.Nullable<int> DP_EmailedRecords
		{
			get
			{
				return this._DP_EmailedRecords;
			}
			set
			{
				if ((this._DP_EmailedRecords != value))
				{
					this.OnDP_EmailedRecordsChanging(value);
					this.SendPropertyChanging();
					this._DP_EmailedRecords = value;
					this.SendPropertyChanged("DP_EmailedRecords");
					this.OnDP_EmailedRecordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_ReturnedRecords", DbType="Int")]
		public System.Nullable<int> DP_ReturnedRecords
		{
			get
			{
				return this._DP_ReturnedRecords;
			}
			set
			{
				if ((this._DP_ReturnedRecords != value))
				{
					this.OnDP_ReturnedRecordsChanging(value);
					this.SendPropertyChanging();
					this._DP_ReturnedRecords = value;
					this.SendPropertyChanged("DP_ReturnedRecords");
					this.OnDP_ReturnedRecordsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DP_PrioritySets", DbType="Int")]
		public System.Nullable<int> DP_PrioritySets
		{
			get
			{
				return this._DP_PrioritySets;
			}
			set
			{
				if ((this._DP_PrioritySets != value))
				{
					this.OnDP_PrioritySetsChanging(value);
					this.SendPropertyChanging();
					this._DP_PrioritySets = value;
					this.SendPropertyChanged("DP_PrioritySets");
					this.OnDP_PrioritySetsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recon_JobNumbers")]
	public partial class Recon_JobNumber : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _JN_UID;
		
		private System.Nullable<System.DateTime> _JN_Month;
		
		private System.Nullable<int> _JN_JobNumber;
		
		private System.Nullable<int> _JU_ClientID;
		
		private System.Nullable<int> _JU_Division;
		
		private string _JN_Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnJN_UIDChanging(int value);
    partial void OnJN_UIDChanged();
    partial void OnJN_MonthChanging(System.Nullable<System.DateTime> value);
    partial void OnJN_MonthChanged();
    partial void OnJN_JobNumberChanging(System.Nullable<int> value);
    partial void OnJN_JobNumberChanged();
    partial void OnJU_ClientIDChanging(System.Nullable<int> value);
    partial void OnJU_ClientIDChanged();
    partial void OnJU_DivisionChanging(System.Nullable<int> value);
    partial void OnJU_DivisionChanged();
    partial void OnJN_CommentChanging(string value);
    partial void OnJN_CommentChanged();
    #endregion
		
		public Recon_JobNumber()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JN_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int JN_UID
		{
			get
			{
				return this._JN_UID;
			}
			set
			{
				if ((this._JN_UID != value))
				{
					this.OnJN_UIDChanging(value);
					this.SendPropertyChanging();
					this._JN_UID = value;
					this.SendPropertyChanged("JN_UID");
					this.OnJN_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JN_Month", DbType="DateTime")]
		public System.Nullable<System.DateTime> JN_Month
		{
			get
			{
				return this._JN_Month;
			}
			set
			{
				if ((this._JN_Month != value))
				{
					this.OnJN_MonthChanging(value);
					this.SendPropertyChanging();
					this._JN_Month = value;
					this.SendPropertyChanged("JN_Month");
					this.OnJN_MonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JN_JobNumber", DbType="Int")]
		public System.Nullable<int> JN_JobNumber
		{
			get
			{
				return this._JN_JobNumber;
			}
			set
			{
				if ((this._JN_JobNumber != value))
				{
					this.OnJN_JobNumberChanging(value);
					this.SendPropertyChanging();
					this._JN_JobNumber = value;
					this.SendPropertyChanged("JN_JobNumber");
					this.OnJN_JobNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JU_ClientID", DbType="Int")]
		public System.Nullable<int> JU_ClientID
		{
			get
			{
				return this._JU_ClientID;
			}
			set
			{
				if ((this._JU_ClientID != value))
				{
					this.OnJU_ClientIDChanging(value);
					this.SendPropertyChanging();
					this._JU_ClientID = value;
					this.SendPropertyChanged("JU_ClientID");
					this.OnJU_ClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JU_Division", DbType="Int")]
		public System.Nullable<int> JU_Division
		{
			get
			{
				return this._JU_Division;
			}
			set
			{
				if ((this._JU_Division != value))
				{
					this.OnJU_DivisionChanging(value);
					this.SendPropertyChanging();
					this._JU_Division = value;
					this.SendPropertyChanged("JU_Division");
					this.OnJU_DivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JN_Comment", DbType="VarChar(100)")]
		public string JN_Comment
		{
			get
			{
				return this._JN_Comment;
			}
			set
			{
				if ((this._JN_Comment != value))
				{
					this.OnJN_CommentChanging(value);
					this.SendPropertyChanging();
					this._JN_Comment = value;
					this.SendPropertyChanged("JN_Comment");
					this.OnJN_CommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recon_DocType")]
	public partial class Recon_DocType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _DT_UID;
		
		private string _DT_Description;
		
		private System.Nullable<int> _DT_ClientID;
		
		private string _DT_DocType;
		
		private System.Nullable<decimal> _DT_UnitCharge;
		
		private System.Nullable<int> _DT_Division;
		
		private System.Nullable<int> _DT_DisplayOrder;
		
		private System.Nullable<int> _DT_DisplayIOLog;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDT_UIDChanging(int value);
    partial void OnDT_UIDChanged();
    partial void OnDT_DescriptionChanging(string value);
    partial void OnDT_DescriptionChanged();
    partial void OnDT_ClientIDChanging(System.Nullable<int> value);
    partial void OnDT_ClientIDChanged();
    partial void OnDT_DocTypeChanging(string value);
    partial void OnDT_DocTypeChanged();
    partial void OnDT_UnitChargeChanging(System.Nullable<decimal> value);
    partial void OnDT_UnitChargeChanged();
    partial void OnDT_DivisionChanging(System.Nullable<int> value);
    partial void OnDT_DivisionChanged();
    partial void OnDT_DisplayOrderChanging(System.Nullable<int> value);
    partial void OnDT_DisplayOrderChanged();
    partial void OnDT_DisplayIOLogChanging(System.Nullable<int> value);
    partial void OnDT_DisplayIOLogChanged();
    #endregion
		
		public Recon_DocType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int DT_UID
		{
			get
			{
				return this._DT_UID;
			}
			set
			{
				if ((this._DT_UID != value))
				{
					this.OnDT_UIDChanging(value);
					this.SendPropertyChanging();
					this._DT_UID = value;
					this.SendPropertyChanged("DT_UID");
					this.OnDT_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Description", DbType="VarChar(50)")]
		public string DT_Description
		{
			get
			{
				return this._DT_Description;
			}
			set
			{
				if ((this._DT_Description != value))
				{
					this.OnDT_DescriptionChanging(value);
					this.SendPropertyChanging();
					this._DT_Description = value;
					this.SendPropertyChanged("DT_Description");
					this.OnDT_DescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_ClientID", DbType="Int")]
		public System.Nullable<int> DT_ClientID
		{
			get
			{
				return this._DT_ClientID;
			}
			set
			{
				if ((this._DT_ClientID != value))
				{
					this.OnDT_ClientIDChanging(value);
					this.SendPropertyChanging();
					this._DT_ClientID = value;
					this.SendPropertyChanged("DT_ClientID");
					this.OnDT_ClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_DocType", DbType="VarChar(50)")]
		public string DT_DocType
		{
			get
			{
				return this._DT_DocType;
			}
			set
			{
				if ((this._DT_DocType != value))
				{
					this.OnDT_DocTypeChanging(value);
					this.SendPropertyChanging();
					this._DT_DocType = value;
					this.SendPropertyChanged("DT_DocType");
					this.OnDT_DocTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_UnitCharge", DbType="Money")]
		public System.Nullable<decimal> DT_UnitCharge
		{
			get
			{
				return this._DT_UnitCharge;
			}
			set
			{
				if ((this._DT_UnitCharge != value))
				{
					this.OnDT_UnitChargeChanging(value);
					this.SendPropertyChanging();
					this._DT_UnitCharge = value;
					this.SendPropertyChanged("DT_UnitCharge");
					this.OnDT_UnitChargeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_Division", DbType="Int")]
		public System.Nullable<int> DT_Division
		{
			get
			{
				return this._DT_Division;
			}
			set
			{
				if ((this._DT_Division != value))
				{
					this.OnDT_DivisionChanging(value);
					this.SendPropertyChanging();
					this._DT_Division = value;
					this.SendPropertyChanged("DT_Division");
					this.OnDT_DivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_DisplayOrder", DbType="Int")]
		public System.Nullable<int> DT_DisplayOrder
		{
			get
			{
				return this._DT_DisplayOrder;
			}
			set
			{
				if ((this._DT_DisplayOrder != value))
				{
					this.OnDT_DisplayOrderChanging(value);
					this.SendPropertyChanging();
					this._DT_DisplayOrder = value;
					this.SendPropertyChanged("DT_DisplayOrder");
					this.OnDT_DisplayOrderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DT_DisplayIOLog", DbType="Int")]
		public System.Nullable<int> DT_DisplayIOLog
		{
			get
			{
				return this._DT_DisplayIOLog;
			}
			set
			{
				if ((this._DT_DisplayIOLog != value))
				{
					this.OnDT_DisplayIOLogChanging(value);
					this.SendPropertyChanging();
					this._DT_DisplayIOLog = value;
					this.SendPropertyChanged("DT_DisplayIOLog");
					this.OnDT_DisplayIOLogChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recon_Divisions")]
	public partial class Recon_Division : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _D_UID;
		
		private System.Nullable<int> _D_ClientID;
		
		private System.Nullable<int> _D_Division;
		
		private string _D_Comment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnD_UIDChanging(int value);
    partial void OnD_UIDChanged();
    partial void OnD_ClientIDChanging(System.Nullable<int> value);
    partial void OnD_ClientIDChanged();
    partial void OnD_DivisionChanging(System.Nullable<int> value);
    partial void OnD_DivisionChanged();
    partial void OnD_CommentChanging(string value);
    partial void OnD_CommentChanged();
    #endregion
		
		public Recon_Division()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int D_UID
		{
			get
			{
				return this._D_UID;
			}
			set
			{
				if ((this._D_UID != value))
				{
					this.OnD_UIDChanging(value);
					this.SendPropertyChanging();
					this._D_UID = value;
					this.SendPropertyChanged("D_UID");
					this.OnD_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_ClientID", DbType="Int")]
		public System.Nullable<int> D_ClientID
		{
			get
			{
				return this._D_ClientID;
			}
			set
			{
				if ((this._D_ClientID != value))
				{
					this.OnD_ClientIDChanging(value);
					this.SendPropertyChanging();
					this._D_ClientID = value;
					this.SendPropertyChanged("D_ClientID");
					this.OnD_ClientIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Division", DbType="Int")]
		public System.Nullable<int> D_Division
		{
			get
			{
				return this._D_Division;
			}
			set
			{
				if ((this._D_Division != value))
				{
					this.OnD_DivisionChanging(value);
					this.SendPropertyChanging();
					this._D_Division = value;
					this.SendPropertyChanged("D_Division");
					this.OnD_DivisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D_Comment", DbType="VarChar(100)")]
		public string D_Comment
		{
			get
			{
				return this._D_Comment;
			}
			set
			{
				if ((this._D_Comment != value))
				{
					this.OnD_CommentChanging(value);
					this.SendPropertyChanging();
					this._D_Comment = value;
					this.SendPropertyChanged("D_Comment");
					this.OnD_CommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Recon_Tracking")]
	public partial class Recon_Tracking : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _T_UID;
		
		private int _DR_UID;
		
		private string _TrackingNo;
		
		private bool _Flag;
		
		private string _AddressLine1;
		
		private string _AddressLine2;
		
		private string _AddressLine3;
		
		private string _Subub;
		
		private string _State;
		
		private string _Postcode;
		
		private string _FileName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnT_UIDChanging(int value);
    partial void OnT_UIDChanged();
    partial void OnDR_UIDChanging(int value);
    partial void OnDR_UIDChanged();
    partial void OnTrackingNoChanging(string value);
    partial void OnTrackingNoChanged();
    partial void OnFlagChanging(bool value);
    partial void OnFlagChanged();
    partial void OnAddressLine1Changing(string value);
    partial void OnAddressLine1Changed();
    partial void OnAddressLine2Changing(string value);
    partial void OnAddressLine2Changed();
    partial void OnAddressLine3Changing(string value);
    partial void OnAddressLine3Changed();
    partial void OnSububChanging(string value);
    partial void OnSububChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnPostcodeChanging(string value);
    partial void OnPostcodeChanged();
    partial void OnFileNameChanging(string value);
    partial void OnFileNameChanged();
    #endregion
		
		public Recon_Tracking()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_T_UID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int T_UID
		{
			get
			{
				return this._T_UID;
			}
			set
			{
				if ((this._T_UID != value))
				{
					this.OnT_UIDChanging(value);
					this.SendPropertyChanging();
					this._T_UID = value;
					this.SendPropertyChanged("T_UID");
					this.OnT_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR_UID", DbType="Int NOT NULL")]
		public int DR_UID
		{
			get
			{
				return this._DR_UID;
			}
			set
			{
				if ((this._DR_UID != value))
				{
					this.OnDR_UIDChanging(value);
					this.SendPropertyChanging();
					this._DR_UID = value;
					this.SendPropertyChanged("DR_UID");
					this.OnDR_UIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrackingNo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string TrackingNo
		{
			get
			{
				return this._TrackingNo;
			}
			set
			{
				if ((this._TrackingNo != value))
				{
					this.OnTrackingNoChanging(value);
					this.SendPropertyChanging();
					this._TrackingNo = value;
					this.SendPropertyChanged("TrackingNo");
					this.OnTrackingNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Flag", DbType="Bit NOT NULL")]
		public bool Flag
		{
			get
			{
				return this._Flag;
			}
			set
			{
				if ((this._Flag != value))
				{
					this.OnFlagChanging(value);
					this.SendPropertyChanging();
					this._Flag = value;
					this.SendPropertyChanged("Flag");
					this.OnFlagChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="VarChar(60)")]
		public string AddressLine1
		{
			get
			{
				return this._AddressLine1;
			}
			set
			{
				if ((this._AddressLine1 != value))
				{
					this.OnAddressLine1Changing(value);
					this.SendPropertyChanging();
					this._AddressLine1 = value;
					this.SendPropertyChanged("AddressLine1");
					this.OnAddressLine1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine2", DbType="VarChar(60)")]
		public string AddressLine2
		{
			get
			{
				return this._AddressLine2;
			}
			set
			{
				if ((this._AddressLine2 != value))
				{
					this.OnAddressLine2Changing(value);
					this.SendPropertyChanging();
					this._AddressLine2 = value;
					this.SendPropertyChanged("AddressLine2");
					this.OnAddressLine2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine3", DbType="VarChar(60)")]
		public string AddressLine3
		{
			get
			{
				return this._AddressLine3;
			}
			set
			{
				if ((this._AddressLine3 != value))
				{
					this.OnAddressLine3Changing(value);
					this.SendPropertyChanging();
					this._AddressLine3 = value;
					this.SendPropertyChanged("AddressLine3");
					this.OnAddressLine3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Subub", DbType="VarChar(30)")]
		public string Subub
		{
			get
			{
				return this._Subub;
			}
			set
			{
				if ((this._Subub != value))
				{
					this.OnSububChanging(value);
					this.SendPropertyChanging();
					this._Subub = value;
					this.SendPropertyChanged("Subub");
					this.OnSububChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(3)")]
		public string State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Postcode", DbType="VarChar(4)")]
		public string Postcode
		{
			get
			{
				return this._Postcode;
			}
			set
			{
				if ((this._Postcode != value))
				{
					this.OnPostcodeChanging(value);
					this.SendPropertyChanging();
					this._Postcode = value;
					this.SendPropertyChanged("Postcode");
					this.OnPostcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FileName", DbType="VarChar(100)")]
		public string FileName
		{
			get
			{
				return this._FileName;
			}
			set
			{
				if ((this._FileName != value))
				{
					this.OnFileNameChanging(value);
					this.SendPropertyChanging();
					this._FileName = value;
					this.SendPropertyChanged("FileName");
					this.OnFileNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
