<?xml version="1.0" encoding="utf-8"?><Database Name="SimplyEnergy" Class="SimplyEnergyDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DB1\DOC1;Initial Catalog=SimplyEnergy;Integrated Security=True" SettingsObjectName="DataAccessLayer.Properties.Settings" SettingsPropertyName="SimplyEnergyConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.stella_ERSRates" Member="stella_ERSRates">
    <Type Name="stella_ERSRate">
      <Column Name="UID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductCode" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DetailsField" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.web_DocType" Member="web_DocTypes">
    <Type Name="web_DocType">
      <Column Name="DocTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DocTypeDescription" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>